;; Generated by scripts/test/generate_atomic_spec_test.py. Do not edit manually.

(module
  (memory 1 1)

  ;; Memory index must come before memory ordering if present.
  ;; Both immediates are optional; an omitted memory ordering will be treated as seqcst.
  (func $test-all-ops
    (drop (i32.atomic.load (i32.const 0)))
    (drop (i32.atomic.load acqrel (i32.const 0)))
    (drop (i32.atomic.load seqcst (i32.const 0)))
  )
)

(assert_malformed
  (module quote
    "(memory 1 1 shared) (func $i32load (drop (i32.load acqrel (i32.const 51))))"
  )
  "unexpected token")

