;; Generated by test/core/acquire-release-atomics/meta/generate_atomic_spec_test.py.
;; Do not edit manually.

(module
  (memory 1 1)

  (func $test-all-ops
    (drop (i32.atomic.load (i32.const 0)))
    (drop (i32.atomic.load acqrel (i32.const 0)))
    (drop (i32.atomic.load seqcst (i32.const 0)))
  )
)

(assert_malformed
  (module quote
    "(memory 1 1 shared) (func $i32load (drop (i32.load acqrel (i32.const 51))))"
  )
  "unexpected token")

(module binary
  "\00asm\01\00\00\00" ;; Wasm header
  "\01\04\01" ;; Type section
    "\60\00\00" ;; $test-all-ops type
  "\03\02\01\00" ;; Function section
  "\05\04\01" ;; Memory section
    "\01\01\01" ;; (memory 1 1)
  "\0a\1b\01" ;; Code section
  "\19\00" ;; func $test-all-ops

    "\41\00" ;; (i32.const 0)
    "\fe\10" ;; i32.atomic.load
    "\02" ;; Alignment of 2
    "\00" ;; offset
    "\1a" ;; drop

    "\41\00" ;; (i32.const 0)
    "\fe\10" ;; i32.atomic.load
    "\12" ;; Alignment of 2 with bit 4 set indicating that an ordering immediate follows
    "\01" ;; acqrel memory ordering
    "\00" ;; offset
    "\1a" ;; drop

    "\41\00" ;; (i32.const 0)
    "\fe\10" ;; i32.atomic.load
    "\12" ;; Alignment of 2 with bit 4 set indicating that an ordering immediate follows
    "\00" ;; seqcst memory ordering
    "\00" ;; offset
    "\1a" ;; drop

    "\0b" ;; end
)
